class PV_55p8:
    _value: int
    
    def __init__(self, value: float = 0) -> None: ...
    
    def __eq__(self, __value: PV_55p8) -> bool: ...
    def __ne__(self, __value: PV_55p8) -> bool: ...
    def __gt__(self, __value: PV_55p8) -> bool: ...
    def __lt__(self, __value: PV_55p8) -> bool: ...
    def __ge__(self, __value: PV_55p8) -> bool: ...
    def __le__(self, __value: PV_55p8) -> bool: ...

    def __hash__(self) -> int: ...

    def __str__(self) -> str: ...

    def strvalue(self) -> str: ...
