from .pv_num import PV_num

class PV_55p8(PV_num):
    _value: int
    
    def __init__(self, value: float | PV_num = 0) -> None: ...
    
    def __eq__(self, __value: PV_num) -> bool: ...
    def __ne__(self, __value: PV_num) -> bool: ...
    def __gt__(self, __value: PV_num) -> bool: ...
    def __lt__(self, __value: PV_num) -> bool: ...
    def __ge__(self, __value: PV_num) -> bool: ...
    def __le__(self, __value: PV_num) -> bool: ...

    def __hash__(self) -> int: ...

    def __str__(self) -> str: ...

    def strvalue(self) -> str: ...
