#include "pvc_PV_num.h"

int pT77(pvc_PV_55p8 *self, const pvc_PV_55p8 *other)
{
    if (!self || !other) return -1;
    self->_1 = other->_1;
    return 0;
}

int pT78(pvc_PV_55p8 *self, const pvc_PV_119p8 *other)
{
    if (!self || !other) return -1;
    if (other->_1 == 0 && other->_2 < (uint64_t)INT64_MIN)
    {
        self->_1 = (int64_t)other->_2;
        return 0;
    }
    if (other->_1 == -1 && (int64_t)other->_2 < 0)
    {
        self->_1 = (int64_t)other->_2;
        return 0;
    }
    self->_1 = 0;
    return 1;
}

int pT87(pvc_PV_119p8 *self, const pvc_PV_55p8 *other)
{
    if (!self || !other) return -1;
    self->_1 = (other->_1 >= 0 ? 0ll: -1ll);
    self->_2 = (uint64_t)other->_1;
    return 0;
}

int pT88(pvc_PV_119p8 *self, const pvc_PV_119p8 *other)
{
    if (!self || !other) return -1;
    self->_1 = other->_1;
    self->_2 = other->_2;
    return 0;
}

const PVcTTF pvc_type_trans_func[MAX_DERIVED][MAX_DERIVED] = {
    {(PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL},
    {(PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL},
    {(PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL},
    {(PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL},
    {(PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL},
    {(PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL},
    {(PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL},
    {(PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)pT77, (PVcTTF)pT78, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL},
    {(PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)pT87, (PVcTTF)pT88, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL},
    {(PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL},
    {(PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL},
    {(PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL},
    {(PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL},
    {(PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL},
    {(PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL},
    {(PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL},
    {(PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL, (PVcTTF)NULL}
};
