name: C test pvc_add_overflow
run-name: C test pvc_add_overflow triggered bt ${{ github.actor }}
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  label:
    types:
      - created
      - edited
      - deleted
  push:
    branches:
      - main
      - "**"
  schedule:
    - cron: "17 2 * * *"
jobs:
  run-tests-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compile PVOs/pvc_defines.c
        run: gcc -Wall -Wextra -c src/PowerViolenceObjects/pvc_defines.c -o pvc_defines-ubuntu.o
      - name: Compile PVOs/pvc_add_overflow.c
        run: gcc -Wall -Wextra -c tests/ctests/ct_pvc_add_overflow.c -o ct_pvc_add_overflow-ubuntu.o -Isrc/PowerViolenceObjects/PV_num/PV_fixed
      - name: link
        run: gcc ct_pvc_add_overflow-ubuntu.o pvc_defines-ubuntu.o -o ct_pvc_add_overflow-ubuntu
      - name: Run
        run: ./ct_pvc_add_overflow-ubuntu

  run-tests-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compile PVOs/pvc_defines.c
        run: gcc -Wall -Wextra -c src/PowerViolenceObjects/pvc_defines.c -o pvc_defines-macos.o
      - name: Compile PVOs/pvc_add_overflow.c
        run: gcc -Wall -Wextra -c tests/ctests/ct_pvc_add_overflow.c -o ct_pvc_add_overflow-macos.o -Isrc/PowerViolenceObjects/PV_num/PV_fixed
      - name: link
        run: gcc ct_pvc_add_overflow-macos.o pvc_defines-macos.o -o ct_pvc_add_overflow-macos
      - name: Run
        run: ./ct_pvc_add_overflow-macos

  run-tests-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compile PVOs/pvc_defines.c
        run: gcc -Wall -Wextra -c src/PowerViolenceObjects/pvc_defines.c -o pvc_defines-windows.o
      - name: Compile PVOs/pvc_add_overflow.c
        run: gcc -Wall -Wextra -c tests/ctests/ct_pvc_add_overflow.c -o ct_pvc_add_overflow-windows.o -Isrc/PowerViolenceObjects/PV_num/PV_fixed
      - name: link
        run: gcc ct_pvc_add_overflow-windows.o pvc_defines-windows.o -o ct_pvc_add_overflow-windows
      - name: Run
        run: ./ct_pvc_add_overflow-windows
        