name: C test pvc_PV_119p8
run-name: C test pvc_PV_119p8 triggered bt ${{ github.actor }}
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  label:
    types:
      - created
      - edited
      - deleted
  push:
    branches:
      - main
      - "**"
  schedule:
    - cron: "17 2 * * *"
jobs:
  compile-source:
    name: compile source to *.o
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compile PVOs/pvc_PV_119p8.c
        run: gcc -Wall -Wextra -c src/PowerViolenceObjects/pvc_PV_119p8.c -o pvc_PV_119p8.o
    
  run-test:
    needs: compile-source
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Compile to *.o
        run: gcc -Wall -Wextra -c tests/ctests/pvc_PV_119p8.c -o ct_pvc_PV_119p8.o -Isrc/PowerViolenceObjects
      - name: link
        run: gcc pvc_PV_119p8.o ct_pvc_PV_119p8.o -o ct_pvc_PV_119p8
      - name: Run
        run: ./ct_pvc_PV_119p8

