name: C test powerobject
run-name: C test powerobject triggered bt ${{ github.actor }}
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  label:
    types:
      - created
      - edited
      - deleted
  push:
    branches:
      - main
      - "**"
  schedule:
    - cron: "17 2 * * *"
jobs:
  compile-source:
    name: compile source to *.o
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compile PVOs/pv_c_powerobjects.c
        run: gcc -Wall -Wextra -c src/PowerViolenceObjects/pv_c_powerobject.c -o pvc_powerobject.o
    
  run-test:
    needs: compile-source
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Compile to *.o
        run: gcc -Wall -Wextra -c tests/ctests/powerobject.c -o ct_powerobject.o -Isrc/PowerViolenceObjects
      - name: link
        run: gcc pvc_powerobject.o ct_powerobject.o -o ct_powerobject
      - name: Run
        run: ./ct_powerobject

